project:
  type: website
  output-dir: docs

website:
  title: "Thoughts From A Lake"
  site-url: https://lekhbhatia.github.io/
  search: true
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true