project:
  type: website
  output-dir: docs

website:
  title: "Thoughts by the Lake"
  site-url: https://lekhbhatia.github.io/
  search: true
  navbar:
    left:
      - href: blog/index.qmd
        text: Posts

format:
  html:
    theme:
      - cosmo
      - brand
    css: style.css